name = "chat4"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-07-21"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]

[[routes]]
pattern = "https://chat4.tru-bone.workers.dev/"
zone_name = "hwmnbn.me"

[[routes]]
pattern = "http://chat4.tru-bone.workers.dev/"
zone_name = "hwmnbn.me"

[placement]
mode = "smart"

[[migrations]]
new_classes = [ "PlaywrightMCP" ]
tag = "latest"

[observability]
enabled = true
head_sampling_rate = 1

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true

[assets]
directory = "public"
binding = "ASSETS"
[ai]
binding = "AI"

[vars]
DEEPSEEK_API_KEY = "sk-6db33fafb1c844a4abcf5f054e93fb36"
AI_GATEWAY_NAME = "moongate"
DEFAULT_MODEL_ID = "deepseek-v3.1"
DEFAULT_SYSTEM_PROMPT = "You are a helpful AI agent."
OPENAI_API_KEY = "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" # if OpenRouter is also OpenAI key based
AI_GATEWAY_ENDPOINT = "https://gateway.ai.cloudflare.com/v1/moongate"
HF_API_KEY = ""
SERVICE_API_KEY = ""

[[services]]
binding = "bolt"
service = "bolt"
environment = "production"

[[services]]
binding = "mcpservice"
service = "playwmcp"
environment = "production"
entrypoint = "PlaywrightMCP"

[[r2_buckets]]
binding = "levister"
bucket_name = "notlevidata"

[[r2_buckets]]
binding = "whobcode"
bucket_name = "whobdata"

[[durable_objects.bindings]]
name = "mcp"
class_name = "PlaywrightMCP"
script_name = "playwmcp"

[browser]
binding = "render"
